USE alliraa;

CREATE TABLE IF NOT EXISTS store_branding (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  data_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
